# Generated by Django 6.1.1 on 2026-09-18 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject_type', models.CharField(choices=[('seller', 'Seller'), ('listing', 'Listing'), ('website', 'Website'), ('business', 'Business'), ('freelancer', 'Freelancer'), ('rental', 'Rental'), ('message', 'Message'), ('other', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('subject_name', models.CharField(blank=True, max_length=255)),
                ('subject_phone', models.CharField(blank=True, max_length=32)),
                ('subject_email', models.CharField(blank=True, max_length=255)),
                ('subject_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8, null=True)),
                ('summary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigation_subjects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('domain', 'Domain'), ('username', 'Username'), ('url', 'URL'), ('social_handle', 'Social Handle')], max_length=16)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='investigations.investigation')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('ai_suggested', 'AI Suggested'), ('moderator_confirmed', 'Moderator Confirmed')], default='ai_suggested', max_length=24)),
                ('confidence_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_connections', to=settings.AUTH_USER_MODEL)),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investigations.identifier')),
                ('investigation', models.ForeignKey(help_text='The *other* investigation this identifier also appears in.', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investigations.investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('screenshot', 'Screenshot'), ('image', 'Image'), ('document', 'Document'), ('url', 'URL'), ('text', 'Text')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('text_value', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.investigation')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('extraction', 'Extraction'), ('language_analysis', 'Language Analysis'), ('similarity', 'Similarity'), ('summary', 'Summary')], max_length=24)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='investigations.evidence')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('category', models.CharField(choices=[('Payment', 'Payment'), ('Content', 'Content'), ('Technical', 'Technical'), ('Network', 'Network')], max_length=16)),
                ('score_impact', models.SmallIntegerField(default=0)),
                ('detected_by', models.CharField(choices=[('ai', 'AI'), ('backend_rule', 'Backend Rule')], default='backend_rule', max_length=16)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_signals', to='investigations.investigation')),
            ],
        ),
    ]
